version: 2
jobs:
  projector-core:
    docker:
      - image: markhibberd/haskell-circleci:latest
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - 'mafia-'
      - run:
          name: 'cabal'
          command: 'cabal update'
      - run:
          name: 'build'
          command: 'cd projector-core && mafia build'
      - save_cache:
          key: 'mafia-{{ epoch }}'
          paths:
            - '/root/.mafia'
      - run:
          name: 'test'
          command: 'cd projector-core && mafia test'
  projector-cli:
    docker:
      - image: markhibberd/haskell-circleci:latest
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - 'mafia-'
      - run:
          name: 'cabal'
          command: 'cabal update'
      - run:
          name: 'libtinfo'
          command: 'apt-get install -y libtinfo-dev'
      - run:
          name: 'build'
          command: 'cd projector-cli && mafia build'
      - save_cache:
          key: 'mafia-{{ epoch }}'
          paths:
            - '/root/.mafia'
      - run:
          name: 'test'
          command: 'cd projector-cli && mafia test'
  projector-html:
    docker:
      - image: markhibberd/haskell-circleci:latest
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - 'mafia-'
      - run:
          name: 'cabal'
          command: 'cabal update'
      - run:
          name: 'build'
          command: 'cd projector-html && mafia build'
      - save_cache:
          key: 'mafia-{{ epoch }}'
          paths:
            - '/root/.mafia'
      - run:
          name: 'test'
          command: 'cd projector-html && mafia test'
      - run:
          name: 'cabal'
          command: 'cabal update'
  projector-html-haskell:
    docker:
      - image: markhibberd/haskell-circleci:latest
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - 'mafia-'
      - run:
          name: 'cabal'
          command: 'cabal update'
      - run:
          name: 'build'
          command: 'cd projector-html-haskell && mafia build'
      - save_cache:
          key: 'mafia-{{ epoch }}'
          paths:
            - '/root/.mafia'
      - run:
          name: 'test'
          command: 'cd projector-html-haskell && mafia test'
  projector-html-purs:
    docker:
      - image: markhibberd/haskell-circleci:latest
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - 'mafia-'
      - run:
          name: 'cabal'
          command: 'cabal update'
      - run:
          name: 'build'
          command: 'cd projector-html-purs && mafia build'
      - save_cache:
          key: 'mafia-{{ epoch }}'
          paths:
            - '/root/.mafia'
      - run:
          name: 'test'
          command: 'cd projector-html-purs && echo "no tests as there is no npm runtime at the moment"'
  projector-html-runtime-hs:
    docker:
      - image: markhibberd/haskell-circleci:latest
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - 'mafia-'
      - run:
          name: 'cabal'
          command: 'cabal update'
      - run:
          name: 'build'
          command: 'cd projector-html-runtime-hs && mafia build'
      - save_cache:
          key: 'mafia-{{ epoch }}'
          paths:
            - '/root/.mafia'
      - run:
          name: 'test'
          command: 'cd projector-html-runtime-hs && mafia test'
  cabal-check:
    docker:
      - image: markhibberd/haskell-circleci:latest
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'cabal-check'
          command: './bin/check'
  cabal-new-build:
    docker:
      - image: markhibberd/haskell-circleci:latest
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'cabal-update'
          command: 'cabal update'
      - run:
          name: 'cabal-new-build-sanity-check'
          command: './bin/cabal-new-build'
workflows:
  version: 2
  all:
    jobs:
      - projector-core
      - projector-cli
      - projector-html
      - projector-html-haskell
      - projector-html-purs
      - projector-html-runtime-hs
      - cabal-check
      - cabal-new-build
